export default numberColumnType = [
    impressions = 'Impressions',
    clicks = 'Clicks',
    ctr = clicks/impressions,
    spend = 'Spend(USD)',
    sales = 'Sales(USD)',
    acos = spend/sales,
    roas = sales/spend,
    orders = 'Orders',
    cpc = spend/clicks,
    conversionRate = orders/clicks,

    'NTB orders',
    'NTB sales(USD)',
    'Viewable impressions',
    'VCPM(USD)',
    'Sessions',
    'Page views',
    'Units ordered - B2B',
    'Ordered product sales',
    'Ordered product sales - B2B',
    'Total order items',
    'Total order items - B2B',
    'Cost Per Click (CPC)',
    'Spend',
    '7 Day Total Sales ',
    'Total Return on Advertising Spend (RoAS)',
    '7 Day Total Orders (#)',
    '7 Day Total Units (#)',
    '7 Day Conversion Rate',
    '7 Day Advertised SKU Units (#)',
    '7 Day Other SKU Units (#)',
    '7 Day Advertised SKU Sales ',
    '7 Day Other SKU Sales',
    'Price',
    'Sales',
    'Revenue',
    'BSR',
    'FBA Fees',
    'Active Sellers #',
    'Ratings',
    'Review Count',
    'Images',
    'Review velocity',
    'Suggested bid (median)(EUR)',
    'Suggested bid (high)(EUR)',
    'Target bid(EUR)',
    'Spend(EUR)',
    'CPC(EUR)',
    'Sales(EUR)',

    '% of orders NTB',
    '% of sales NTB',
    'Page views percentage',
    'Percentage	Units ordered',
    'Click-Thru Rate (CTR)',
    'Total Advertising Cost of Sales (ACoS) ',
    'Session percentage',
    'Featured Offer (Buy Box)',
    'Unit session percentage',
    'Unit session percentage - B2B',
    'Conversion rate',
]