export const newMetricsSpliter = {
    NTBPercentageOrders: ['%OfOrdersNtb'],
    NTBPercentageSales: ['%OfSalesNtb'],
    acos: ['acos', 'totalAdvertisingCostOfSalesAcos'],
    activeSellers: ['activeSellers'],
    averageBuyBox: ['featuredOfferBuyBox', 'featuredOfferBuyBoxPercentage'],
    averageOfferCount: ['averageOfferCount'],
    averageSalesPerOrder: ['averageSalesPerOrderItem'],
    averageSalesPerOrderB2B: ['averageSalesPerOrderItemB2b'],
    averageSellingPrice: ['averageSellingPrice'],
    averageSellingPriceB2B: ['averageSellingPriceB2b'],
    averageUnitPerOrder: ['averageUnitsPerOrderItem'],
    averageUnitPerOrderB2B: ['averageUnitsPerOrderItemB2b'],
    bsr: ['bsr'],
    cr: ['conversionRate'],
    ctr: ['clickthruRateCtr', 'ctr'],
    fbaFees: ['fbaFees'],
    images: ['images'],
    impression: ['impressions'],
    marketingClicks: ['clicks'],
    marketingSales: ['sales', '7DayTotalSales'],
    marketingUnits: ['7DayTotalUnits', '7DayAdvertisedSkuUnits', '7DayOtherSkuUnits'],
    ntbOrders: ['ntbOrders'],
    orderItemSessionPercentage: ['orderItemSessionPercentage'],
    orderItemSessionPercentageB2B: ['orderItemSessionPercentageB2b'],
    orders: ['orders', '7DayTotalOrders'],
    otherTypeOfSales: ['7DayAdvertisedSkuSales', '7DayOtherSkuSales'],
    pageViewPercentage: ['pageViewsPercentage'],
    percentageUnitOrdered: ['percentageunitsOrdered'],
    price: ['price'],
    rating: ['ratings', 'ranking'],
    revenue: ['revenue'],
    reviewCount: ['reviewCount'],
    roas: ['totalReturnOnAdvertisingSpendRoas', 'roas'],
    sessionPercentage: ['sessionPercentage'],
    totalPageViews: ['pageViews'],
    totalSales: ['orderedProductSales'],
    totalSalesB2B: ['orderedProductSalesB2b'],
    totalSessions: ['sessions'],
    totalUnitOrdered: ['unitsOrdered'],
    totalUnits: ['totalOrderItems'],
    totalUnitsB2B: ['totalOrderItemsB2b'],
    unitOrdered: ['unitOrdered'],
    unitOrderedB2B: ['unitsOrderedB2b'],
    unitSessionPercentage: ['unitSessionPercentage'],
    unitSessionPercentageB2B: ['unitSessionPercentageB2b'],
    viewableImpressions: ['viewableImpressions'],
    weight: ['weight'],
    orderItemSessionPercentageB2b: ['orderItemSessionPercentageB2b'],
    orderItemSessionPercentage: ['orderItemSessionPercentage'],
    vcpm: ['vcpm'],
    budget: ['budget'],
    topOfsearchIs: ['topOfsearchIs'],

    ntbSales: ['ntbSales', 'ntbSalesgbp'],
    spend: ['spend', 'spendgbp'],
    sales: ['sales', 'salesgbp'],
    cpc: ['cpc', 'cpcgbp'],

}