export default numberColumnType = [
    'afn-warehouse-quantity',
    'afn-fulfillable-quantity',
    'afn-unsellable-quantity',
    'afn-reserved-quantity',
    'afn-total-quantity',
    'per-unit-volume',
    'afn-inbound-working-quantity',
    'afn-inbound-shipped-quantity',
    'afn-inbound-receiving-quantity',
    'afn-researching-quantity',
    'afn-reserved-future-supply',
    'afn-future-supply-buyable',
    'your-price',
    'impressions',
    'clicks',
    'orders',
    'roas',
    'ntb orders',
    'viewable impressions',
    'sessions',
    'page views',
    'units ordered - b2b',
    'ordered product sales',
    'ordered product sales - b2b',
    'total order items',
    'total order items - b2b',
    'cost per click (cpc)',
    'spend', '7 day total sales ',
    'total return on advertising spend (roas)',
    '7 day total orders (#)',
    '7 day total units (#)',
    '7 day conversion rate',
    '7 day advertised sku units (#)',
    '7 day other sku units (#)',
    '7 day advertised sku sales ',
    '7 day other sku sales',
    'price',
    'sales',
    'revenue',
    'bsr',
    'fba fees',
    'active sellers #',
    'ratings',
    'review count',
    'images',
    'review velocity',
    'ctr',
    'acos',
    '% of orders ntb',
    '% of sales ntb',
    'page views percentage',
    'percentage units ordered',
    'click-thru rate (ctr)',
    'total advertising cost of sales (acos) ',
    'session percentage',
    'featured offer (buy box)',
    'unit session percentage',
    'unit session percentage - b2b',
    'conversion rate',
    'featured offer (buy box) percentage',
    'units ordered',
    'order item session percentage',
    'order item session percentage - b2b',
    'top-of-search is',
    'topOfsearchIs',
    'average sales per order item',
    'average sales per order item - b2b',
    'average units per order item',
    'average units per order item – b2b',
    'average selling price',
    'average selling price - b2b',
    'average units per order item - b2b',
    'average offer count',

    'budget(usd)',
    'spend(usd)',
    'cpc(usd)',
    'sales(usd)',
    'ntb sales(usd)',
    'vcpm(usd)',
    'suggested bid (median)(usd)',
    'suggested bid (high)(usd)',
    'target bid(usd)',

    'budget(eur)',
    'spend(eur)',
    'cpc(eur)',
    'sales(eur)',
    'ntb sales(eur)',
    'vcpm(eur)',
    'suggested bid (median)(eur)',
    'suggested bid (high)(eur)',
    'target bid(eur)',

    'budget(gbp)',
    'spend(gbp)',
    'cpc(gbp)',
    'sales(gbp)',
    'ntb sales(gbp)',
    'vcpm(gbp)',
    'suggested bid (median)(gbp)',
    'suggested bid (high)(gbp)',
    'target bid(gbp)',
]